<a href="https://colab.research.google.com/github/shwetabhosale15/shweta/blob/main/Deep_Learning_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#deep learning

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/Churn_Modelling.csv')

In [ ]:
df.corr()

RowNumber  CustomerId  CreditScore       Age    Tenure  \
RowNumber         1.000000    0.004202     0.005840  0.000783 -0.006495   
CustomerId        0.004202    1.000000     0.005308  0.009497 -0.014883   
CreditScore       0.005840    0.005308     1.000000 -0.003965  0.000842   
Age               0.000783    0.009497    -0.003965  1.000000 -0.009997   
Tenure           -0.006495   -0.014883     0.000842 -0.009997  1.000000   
Balance          -0.009067   -0.012419     0.006268  0.028308 -0.012254   
NumOfProducts     0.007246    0.016972     0.012238 -0.030680  0.013444   
HasCrCard         0.000599   -0.014025    -0.005458 -0.011721  0.022583   
IsActiveMember    0.012044    0.001665     0.025651  0.085472 -0.028362   
EstimatedSalary  -0.005988    0.015271    -0.001384 -0.007201  0.007784   
Exited           -0.016571   -0.006248    -0.027094  0.285323 -0.014001   

                  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber       -0.009067       0.007246   0.000599        0.012044   
CustomerId      -0.012419       0.016972  -0.014025        0.001665   
CreditScore      0.006268       0.012238  -0.005458        0.025651   
Age              0.028308      -0.030680  -0.011721        0.085472   
Tenure          -0.012254       0.013444   0.022583       -0.028362   
Balance          1.000000      -0.304180  -0.014858       -0.010084   
NumOfProducts   -0.304180       1.000000   0.003183        0.009612   
HasCrCard       -0.014858       0.003183   1.000000       -0.011866   
IsActiveMember  -0.010084       0.009612  -0.011866        1.000000   
EstimatedSalary  0.012797       0.014204  -0.009933       -0.011421   
Exited           0.118533      -0.047820  -0.007138       -0.156128   

                 EstimatedSalary    Exited  
RowNumber              -0.005988 -0.016571  
CustomerId              0.015271 -0.006248  
CreditScore            -0.001384 -0.027094  
Age                    -0.007201  0.285323  
Tenure                  0.007784 -0.014001  
Balance                 0.012797  0.118533  
NumOfProducts           0.014204 -0.047820  
HasCrCard              -0.009933 -0.007138  
IsActiveMember         -0.011421 -0.156128  
EstimatedSalary         1.000000  0.012097  
Exited                  0.012097  1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [ ]:
x=df.iloc[:,3:13].values

In [ ]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
y=df.iloc[:,13].values

In [ ]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
np.unique(x[:,1])

array(['France', 'Germany', 'Spain'], dtype=object)

In [ ]:
np.unique(x[:,2])

array(['Female', 'Male'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()

In [ ]:
x[:,1]=le.fit_transform(x[:,1])

In [ ]:
np.unique(x[:,1])

array([0, 1, 2], dtype=object)

In [ ]:
x[:,2]=le.fit_transform(x[:,2])

In [ ]:
np.unique(x[:,2])

array([0, 1], dtype=object)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
x1=sc.fit_transform(x)

In [ ]:
x1.shape

(10000, 10)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x1,y,test_size=0.2)

In [ ]:
import keras

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
classifier=Sequential()

In [ ]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='relu'))
classifier.compile(optimizer='adam',metrics=['Accuracy'],loss='binary_crossentropy')
classifier.fit(x_train,y_train,batch_size=10,epochs=15)

Epoch 1/15
800/800 [==============================] - 2s 2ms/step - loss: 3.1544 - Accuracy: 0.7955
Epoch 2/15
800/800 [==============================] - 1s 2ms/step - loss: 3.1544 - Accuracy: 0.7955
Epoch 3/15
800/800 [==============================] - 1s 2ms/step - loss: 3.1544 - Accuracy: 0.7955
Epoch 4/15
800/800 [==============================] - 1s 2ms/step - loss: 3.1544 - Accuracy: 0.7955
Epoch 5/15
800/800 [==============================] - 2s 2ms/step - loss: 3.1544 - Accuracy: 0.7955
Epoch 6/15
800/800 [==============================] - 1s 2ms/step - loss: 3.1544 - Accuracy: 0.7955
Epoch 7/15
800/800 [==============================] - 1s 2ms/step - loss: 3.1544 - Accuracy: 0.7955
Epoch 8/15
800/800 [==============================] - 1s 2ms/step - loss: 3.1544 - Accuracy: 0.7955
Epoch 9/15
800/800 [==============================] - 1s 2ms/step - loss: 3.1544 - Accuracy: 0.7955
Epoch 10/15
800/800 [==============================] - 1s 2ms/step - loss: 3.1544 - Accuracy: 0.7955

In [ ]:
y_pred=classifier.predict(x_test)

63/63 [==============================] - 0s 1ms/step


In [ ]:
print(y_pred)

[[1.4275543e-09]
 [3.0542396e-10]
 [2.2313467e-09]
 ...
 [5.7529947e-10]
 [8.0511331e-10]
 [7.2461273e-11]]


In [ ]:
y_pred=(y_pred>0.5)

In [ ]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[1599    0]
 [ 401    0]]


In [ ]:
x_test.shape

(2000, 10)

In [ ]:
1599/2000*100

79.95